export default {

  ECONOMY_CHANGE_COUNT: 'ECONOMY_CHANGE_COUNT',
  ECONOMY_CHANGE_COUNTS: 'ECONOMY_CHANGE_COUNTS',
  ECONOMY_CHANGE_PRODUCTION: 'ECONOMY_CHANGE_PRODUCTION',
  ECONOMY_CHANGE_PRODUCTIONS: 'ECONOMY_CHANGE_PRODUCTIONS',
  ECONOMY_NEXT_GENERATION: 'ECONOMY_NEXT_GENERATION',
  ECONOMY_RESET_ECONOMY: 'ECONOMY_RESET_ECONOMY',

  HISTORY_REDO: 'HISTORY_REDO',
  HISTORY_UNDO: 'HISTORY_UNDO'

}